RETRIEVE,
    STREAM     = OPER,
    CLASS      = OD,
    EXPVER     = 0001,
    DATE       = -1,
    TIME       = 12,
    TYPE       = SSD,
    IDENT      = 57,
    INSTRUMENT = 207,
    PARAM      = 260510,
    CHANNEL    = 9,
    STEP       = 0/TO/144/BY/3,
    TARGET     = "meteosat-10.channel9.grib2"
RETRIEVE,
    STEP       = 150/TO/240/BY/6,
    TARGET     = "meteosat-10.channel9.grib2"